// BASE CSS
import '../semantic/dist/components/site.min.css';
import '../semantic/dist/components/reset.min.css';
// FEATURES
// import '../semantic/dist/components/accordion.min.css';
// import '../semantic/dist/components/checkbox.min.css';
// import '../semantic/dist/components/dropdown.min.css';
// import '../semantic/dist/components/grid.min.css';
// import '../semantic/dist/components/item.min.css';
// import '../semantic/dist/components/message.min.css';
// import '../semantic/dist/components/progress.min.css';
// import '../semantic/dist/components/search.min.css';
// import '../semantic/dist/components/statistic.min.css';
// import '../semantic/dist/components/transition.min.css';
// import '../semantic/dist/components/ad.min.css';
// import '../semantic/dist/components/comment.min.css';
// import '../semantic/dist/components/embed.min.css';
// import '../semantic/dist/components/header.min.css';
// import '../semantic/dist/components/label.min.css';
// import '../semantic/dist/components/modal.min.css';
// import '../semantic/dist/components/rail.min.css';
import '../semantic/dist/components/segment.min.css';
// import '../semantic/dist/components/step.min.css';
// import '../semantic/dist/components/breadcrumb.min.css';
// import '../semantic/dist/components/container.min.css';
// import '../semantic/dist/components/feed.min.css';
// import '../semantic/dist/components/icon.min.css';
// import '../semantic/dist/components/list.min.css';
// import '../semantic/dist/components/nag.min.css';
// import '../semantic/dist/components/rating.min.css';
// import '../semantic/dist/components/shape.min.css';
// import '../semantic/dist/components/sticky.min.css';
// import '../semantic/dist/components/button.min.css';
// import '../semantic/dist/components/dimmer.min.css';
// import '../semantic/dist/components/flag.min.css';
// import '../semantic/dist/components/image.min.css';
// import '../semantic/dist/components/loader.min.css';
// import '../semantic/dist/components/placeholder.min.css';
// import '../semantic/dist/components/sidebar.min.css';
